/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.ResultSet;

import java.sql.Statement;
import java.text.DateFormat;
import java.util.Calendar;
import modelo.Reloj;
import controlador.ConectaBD;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Pizza;


/**
 *
 * @author Gema
 */
public class FrmVentas extends javax.swing.JFrame {

    /**
     * Creates new form FrmVentas
     */
    
    private FrmMonto frmMonto;
    public ArrayList ArregloPizza = new ArrayList();
    private double sumaTotal = 0.0;
    
    public FrmVentas() {
        initComponents();
        
       inicializaTabla(Tabla);
        
        
        Reloj hilo = new Reloj(lbRelojDato);
        hilo.start();
        
        Calendar unCalendario = Calendar.getInstance();
        DateFormat unFormatoFecha = DateFormat.getDateInstance(DateFormat.FULL);
        lbFechaDato.setText("" + unFormatoFecha.format(unCalendario.getTime()));
        
        ConectaBD cnc = new ConectaBD();
        Connection cnx = cnc.conectar();
        
        String capturaPizza = "";
        String sql = "select * from pizzas";
        this.comboPizzas.removeAllItems();
        
        try {
            Statement instruccion = cnx.createStatement();
            ResultSet conjuntoResultados = instruccion.executeQuery(sql);
            
            while(conjuntoResultados.next()){
                capturaPizza = conjuntoResultados.getString("Nombre");
                this.comboPizzas.addItem(capturaPizza);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lbTituloVentas = new javax.swing.JLabel();
        lbNombrePizza = new javax.swing.JLabel();
        comboPizzas = new javax.swing.JComboBox<>();
        btAgregarPizza = new javax.swing.JButton();
        lbRelojDato = new javax.swing.JLabel();
        lbFechaDato = new javax.swing.JLabel();
        lbTotalDato = new javax.swing.JLabel();
        btEliminarPizza = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbTotal = new javax.swing.JLabel();
        btGananciasllama = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btVerTotal = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloVentas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTituloVentas.setForeground(new java.awt.Color(255, 0, 0));
        lbTituloVentas.setText("Ventas");

        lbNombrePizza.setText("Nombre de la Pizza:");

        comboPizzas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPizzasActionPerformed(evt);
            }
        });

        btAgregarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/imagenes/add.PNG"))); // NOI18N
        btAgregarPizza.setText("Agregar");
        btAgregarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarPizzaActionPerformed(evt);
            }
        });

        lbRelojDato.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbRelojDato.setText("Hora: ");

        lbFechaDato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFechaDato.setText("Fecha");

        lbTotalDato.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lbTotalDato.setForeground(new java.awt.Color(0, 0, 255));

        btEliminarPizza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEliminarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/imagenes/eliminar-icono-4399-128.png"))); // NOI18N
        btEliminarPizza.setText("Eliminar");
        btEliminarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarPizzaActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar al Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbTotal.setText("TOTAL:");

        btGananciasllama.setText("Ganancias");
        btGananciasllama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGananciasllamaActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        scrollPane1.add(jScrollPane2);

        btVerTotal.setText("Ver Total de Compra");
        btVerTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(lbTituloVentas))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNombrePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbFechaDato, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbRelojDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btAgregarPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGananciasllama)
                                .addGap(215, 215, 215)
                                .addComponent(lbTotal)
                                .addGap(18, 18, 18)
                                .addComponent(lbTotalDato, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btEliminarPizza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btVerTotal)
                                .addGap(36, 36, 36)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRelojDato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFechaDato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lbTituloVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregarPizza)
                    .addComponent(comboPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombrePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btEliminarPizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTotal)
                            .addComponent(btGananciasllama)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btVerTotal)
                        .addGap(18, 18, 18)
                        .addComponent(lbTotalDato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPizzasActionPerformed
         
        ConectaBD cnc = new ConectaBD();
        Connection cnx = cnc.conectar();
        
        
        try {
            Statement instruccion2 = cnx.createStatement();
            ResultSet rs1 = instruccion2.executeQuery("select * from pizzas where nombre = '"
                    + this.comboPizzas.getSelectedItem()+ "'");
            rs1.next();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_comboPizzasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btEliminarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarPizzaActionPerformed
        eliminarPizza(Tabla.getSelectedRow());
        
        inicializaTabla(Tabla);
    }//GEN-LAST:event_btEliminarPizzaActionPerformed

    private void btGananciasllamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGananciasllamaActionPerformed
        frmMonto.setVisible(true);
    }//GEN-LAST:event_btGananciasllamaActionPerformed

    private void btAgregarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarPizzaActionPerformed
        
        ConectaBD cnc = new ConectaBD();
        Connection cnx = cnc.conectar();
        
        int idPi = 0;
        String nomPi="";
        double precioPi = 0.0;
        String tam = "";
        
        try {
            Statement instruccion3 = cnx.createStatement();
            ResultSet rs1 = instruccion3.executeQuery("select * from pizzas where nombre = '"
                + this.comboPizzas.getSelectedItem()+ "'");
            while(rs1.next()){
                idPi = rs1.getInt("IDPizza");
                nomPi = rs1.getString("Nombre");
                tam = rs1.getString("Tamaño");
                precioPi = rs1.getDouble("Precio");
                
            }
            
            agregarPizza(idPi,nomPi,tam,precioPi);
            inicializaTabla(Tabla);
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btAgregarPizzaActionPerformed

    private void btVerTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerTotalActionPerformed
        lbTotalDato.setText(Double.toString(this.sumaTotal));
    }//GEN-LAST:event_btVerTotalActionPerformed
    
    
    
    
    public void agregarPizza(int idPizza, String nombrePizza,String tamaño, double precioPizza){
            ArregloPizza.add(new Pizza(idPizza, nombrePizza, tamaño, precioPizza));
    }
    
    
    
    
 
       public void eliminarPizza(int indice){
        ArregloPizza.remove(indice);        
    }
    
    
    
    
    //Método para listar los datos en la tabla
    public void inicializaTabla(JTable tabla){
  
        Vector <String> titulos = new Vector<String>();
        Vector <Vector <Object>> data = new Vector <Vector <Object>>();
        sumaTotal = 0.0;
        
        titulos.add("IDPizza");
        titulos.add("Nombre");
        titulos.add("Tamaño");
        titulos.add("Precio");
            
            
        for(int i=0; i<ArregloPizza.size(); i++){
            Vector<Object> row = new Vector<Object>();
            
            row.add( ((Pizza) ArregloPizza.get(i)).getIdPizza() );
            row.add( ((Pizza) ArregloPizza.get(i)).getNombrePizza() );
            row.add( ((Pizza) ArregloPizza.get(i)).getTamaño() );
            row.add( ((Pizza) ArregloPizza.get(i)).getPrecioPizza() );
            
            sumaTotal = sumaTotal + ((Pizza) ArregloPizza.get(i)).getPrecioPizza();
            data.add(row);            
        }
        
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(data, titulos);
        this.establecerModeloJTable(modelo, tabla); 

    }
    
    
    
    
    
    private void establecerModeloJTable(DefaultTableModel modelo, JTable tabla){
        tabla.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btAgregarPizza;
    private javax.swing.JButton btEliminarPizza;
    private javax.swing.JButton btGananciasllama;
    private javax.swing.JButton btVerTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboPizzas;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFechaDato;
    private javax.swing.JLabel lbNombrePizza;
    private javax.swing.JLabel lbRelojDato;
    private javax.swing.JLabel lbTituloVentas;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalDato;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
